version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.13    # Use Python 3.13
    commands:
      - pwd           # Print the working directory
      - ls -la        # List all files/folders 
      - cd backend    # Go inside the /backend folder 
      - pip install --upgrade pip   # Update pip 
      - cp lambda_function.py package/   # Copy lambda function script into "package/"
      - pip install -r requirements.txt --target package   # Install all packages into a folder named "package/"
  build:
    commands:
      - cd package            # Move into "package/" folder
      - zip -r function.zip *   # Zip everything (*) into a zip but not the "package/" directory or top-level folder
      - ls -la        # List all files/folders 
      - mv function.zip ..      # Move zip to backend/
      - ls -la        # List all files/folders 
artifacts:
  files:
    - backend/function.zip    # Tell CodeBuild where zip files is and to upload as the build output
