# Not this will only run if lambda_function.py is modified per the Webhook event filter configured in CodePipeline
version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.13    # Use Python 3.13
  pre_build: # See where we are and move into "/backend" folder
    commands:
      - pwd           # Print the working directory
      - ls -la        # List all files/folders 
      - cd backend    # Go inside the "/backend" folder 
  build: # Set up directory with py file and libraries needed for backend lambda function
    commands:
      - pip install --upgrade pip   # Update pip 
      - mkdir package  # Make "package/" 
      - pip install -r requirements.txt --target package/  # Install all packages into a folder named "package/"
      - mv lambda_function.py package/   # Move lambda function script into "package/"
      - ls -la                           # List all files/folders 
artifacts:
  files:
    - '**/*' # Tell CodeBuild to take all files recursively in "package/" and zip them up into an artifact output zip file
  base-directory: backend/package
