# Not this will only run if lambda_function.py is modified per the Webhook event filter configured in CodePipeline
version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.13    # Use Python 3.13
  pre_build: # See where we are and move into "/backend" folder
    commands:
      - pwd           # Print the working directory
      - ls -la        # List all files/folders 
      - cd backend    # Go inside the "/backend" folder 
  build: # Set up directory with py file and libraries needed for backend lambda function
    commands:
      - pip install --upgrade pip   # Update pip 
      - mkdir package  # Make "package/" 
      #- mv lambda_function.py package/   # Move lambda function script into "package/"
      #- mv requirements.txt package/     # Move requirements file into "package/"
      #- cd package/                      # Move into "package/"
      #- mkdir libraries                  # Make "libraries/"
      #- pip install -r requirements.txt --target libraries/   # Install all packages into a folder named "libraries/"
      - pip install -r requirements.txt --target package/
      - mv lambda_function.py package/
      - cd package
      - zip -r ../my_deployment_package.zip .
      - cd ..
      - zip my_deployment_package.zip lambda_function.py
      #- mv requirements.txt libraries    # Move requirements file into "libraries/" for clean directory tree in "package/"
      #- mv requirements.txt package/
      - ls -la                           # List all files/folders 
artifacts:
  files:
    #- backend/package/**/*    # Tell CodeBuild to take all files recursively in "package/" and upload as the build output 
    - my_deployment_package.zip
    base-directory: backend
