version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.13    # Use Python 3.13
  pre_build: # See where we are and move into /backend folder
    commands:
      - pwd           # Print the working directory
      - ls -la        # List all files/folders 
      - cd backend    # Go inside the /backend folder 
  build: # Set up directory will py file and libraries needed for backend
    commands:
      - pip install --upgrade pip   # Update pip 
      - mkdir package  # Make "package/" 
      - mv lambda_function.py package/   # Copy lambda function script into "package/"
      - mv requirements.txt package/
      - cd package/
      - mkdir libraries
      - pip install -r requirements.txt --target libraries   # Install all packages into a folder named "package/"
      - mv requirements.txt libraries
      - ls -la        # List all files/folders 
      - cd ../..      # return to backend/ folder
      - ls -la        # List all files/folders 
artifacts:
  files:
    - backend/package/**/*    # Tell CodeBuild where zip files is and to upload as the build output 
